package com.project.eum.prodtool.service.constants;

public enum Table {
	
	ACTIVITY,
	ACTIVITY_FIELD,
	ACTIVITY_TYPE,
	ANALYST,
	ANALYST_ACTIVITY,
	ANALYST_ACTIVITY_FIELD_DETAIL,
	ANALYST_LOGIN,
	ANALYST_LOGIN_HISTORY,
	ANALYST_SHIFT_SCHEDULE,
	ANALYST_TEAM,
	ATTENDANCE,
	FIELD,
	REPORT,
	REPORT_TYPE,
	SHIFT_SCHEDULE,
	TEAM,
	TEAM_ACTIVITY;
	
}
